[package]
name = "parser"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://github.com/pascalkuthe/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[lib]
doctest = false
[badges]
maintenance = { status = "actively-developed" }


[dependencies]

# data-structures = {version = "0.0.0", path = "../data_structures" }
drop_bomb = "0.1.5"
stdx = {version="0.0.0", path="../../lib/stdx"}
tokens = {version="0.0.0", path="../tokens"}
