//! Generated by `generate_builtins`, do not edit by hand.

use crate::{
    name::{kw, sysfun, Name},
    nameres::ScopeDefItem,
};
use ahash::AHashMap;
#[derive(Eq, PartialEq, Copy, Clone, Hash, Debug)]
#[allow(nonstandard_style, unreachable_pub)]
#[repr(u8)]
pub enum BuiltIn {
    analysis = 0u8,
    acos = 1u8,
    acosh = 2u8,
    ac_stim = 3u8,
    asin = 4u8,
    asinh = 5u8,
    atan = 6u8,
    atan2 = 7u8,
    atanh = 8u8,
    cos = 9u8,
    cosh = 10u8,
    ddt = 11u8,
    ddx = 12u8,
    exp = 13u8,
    flicker_noise = 14u8,
    floor = 15u8,
    flow = 16u8,
    hypot = 17u8,
    idt = 18u8,
    idtmod = 19u8,
    laplace_nd = 20u8,
    laplace_np = 21u8,
    laplace_zd = 22u8,
    laplace_zp = 23u8,
    limexp = 24u8,
    ln = 25u8,
    log = 26u8,
    max = 27u8,
    min = 28u8,
    noise_table = 29u8,
    noise_table_log = 30u8,
    pow = 31u8,
    sin = 32u8,
    sinh = 33u8,
    sqrt = 34u8,
    tan = 35u8,
    tanh = 36u8,
    last_crossing = 37u8,
    slew = 38u8,
    white_noise = 39u8,
    absdelay = 40u8,
    zi_nd = 41u8,
    zi_np = 42u8,
    zi_zd = 43u8,
    zi_zp = 44u8,
    display = 45u8,
    strobe = 46u8,
    write = 47u8,
    monitor = 48u8,
    debug = 49u8,
    fclose = 50u8,
    fopen = 51u8,
    fdisplay = 52u8,
    fwrite = 53u8,
    fstrobe = 54u8,
    fmonitor = 55u8,
    fgets = 56u8,
    fscanf = 57u8,
    swrite = 58u8,
    sformat = 59u8,
    sscanf = 60u8,
    rewind = 61u8,
    fseek = 62u8,
    ftell = 63u8,
    fflush = 64u8,
    ferror = 65u8,
    feof = 66u8,
    fdebug = 67u8,
    finish = 68u8,
    stop = 69u8,
    fatal = 70u8,
    warning = 71u8,
    error = 72u8,
    info = 73u8,
    abstime = 74u8,
    dist_chi_square = 75u8,
    dist_exponential = 76u8,
    dist_poisson = 77u8,
    dist_uniform = 78u8,
    dist_erlang = 79u8,
    dist_normal = 80u8,
    dist_t = 81u8,
    random = 82u8,
    arandom = 83u8,
    rdist_chi_square = 84u8,
    rdist_exponential = 85u8,
    rdist_poisson = 86u8,
    rdist_uniform = 87u8,
    rdist_erlang = 88u8,
    rdist_normal = 89u8,
    rdist_t = 90u8,
    clog2 = 91u8,
    log10 = 92u8,
    ceil = 93u8,
    temperature = 94u8,
    vt = 95u8,
    simparam = 96u8,
    simprobe = 97u8,
    discontinuity = 98u8,
    limit = 99u8,
    bound_step = 100u8,
    mfactor = 101u8,
    xposition = 102u8,
    yposition = 103u8,
    angle = 104u8,
    hflip = 105u8,
    vflip = 106u8,
    param_given = 107u8,
    port_connected = 108u8,
    analog_node_alias = 109u8,
    analog_port_alias = 110u8,
    value_plusargs = 111u8,
    simparam_str = 112u8,
}
pub fn insert_builtin_scope(dst: &mut AHashMap<Name, ScopeDefItem>) {
    dst.insert(kw::analysis, BuiltIn::analysis.into());
    dst.insert(kw::acos, BuiltIn::acos.into());
    dst.insert(kw::acosh, BuiltIn::acosh.into());
    dst.insert(kw::ac_stim, BuiltIn::ac_stim.into());
    dst.insert(kw::asin, BuiltIn::asin.into());
    dst.insert(kw::asinh, BuiltIn::asinh.into());
    dst.insert(kw::atan, BuiltIn::atan.into());
    dst.insert(kw::atan2, BuiltIn::atan2.into());
    dst.insert(kw::atanh, BuiltIn::atanh.into());
    dst.insert(kw::cos, BuiltIn::cos.into());
    dst.insert(kw::cosh, BuiltIn::cosh.into());
    dst.insert(kw::ddt, BuiltIn::ddt.into());
    dst.insert(kw::ddx, BuiltIn::ddx.into());
    dst.insert(kw::exp, BuiltIn::exp.into());
    dst.insert(kw::flicker_noise, BuiltIn::flicker_noise.into());
    dst.insert(kw::floor, BuiltIn::floor.into());
    dst.insert(kw::flow, BuiltIn::flow.into());
    dst.insert(kw::hypot, BuiltIn::hypot.into());
    dst.insert(kw::idt, BuiltIn::idt.into());
    dst.insert(kw::idtmod, BuiltIn::idtmod.into());
    dst.insert(kw::laplace_nd, BuiltIn::laplace_nd.into());
    dst.insert(kw::laplace_np, BuiltIn::laplace_np.into());
    dst.insert(kw::laplace_zd, BuiltIn::laplace_zd.into());
    dst.insert(kw::laplace_zp, BuiltIn::laplace_zp.into());
    dst.insert(kw::limexp, BuiltIn::limexp.into());
    dst.insert(kw::ln, BuiltIn::ln.into());
    dst.insert(kw::log, BuiltIn::log.into());
    dst.insert(kw::max, BuiltIn::max.into());
    dst.insert(kw::min, BuiltIn::min.into());
    dst.insert(kw::noise_table, BuiltIn::noise_table.into());
    dst.insert(kw::noise_table_log, BuiltIn::noise_table_log.into());
    dst.insert(kw::pow, BuiltIn::pow.into());
    dst.insert(kw::sin, BuiltIn::sin.into());
    dst.insert(kw::sinh, BuiltIn::sinh.into());
    dst.insert(kw::sqrt, BuiltIn::sqrt.into());
    dst.insert(kw::tan, BuiltIn::tan.into());
    dst.insert(kw::tanh, BuiltIn::tanh.into());
    dst.insert(kw::last_crossing, BuiltIn::last_crossing.into());
    dst.insert(kw::slew, BuiltIn::slew.into());
    dst.insert(kw::white_noise, BuiltIn::white_noise.into());
    dst.insert(kw::absdelay, BuiltIn::absdelay.into());
    dst.insert(kw::zi_nd, BuiltIn::zi_nd.into());
    dst.insert(kw::zi_np, BuiltIn::zi_np.into());
    dst.insert(kw::zi_zd, BuiltIn::zi_zd.into());
    dst.insert(kw::zi_zp, BuiltIn::zi_zp.into());
    dst.insert(sysfun::display, BuiltIn::display.into());
    dst.insert(sysfun::strobe, BuiltIn::strobe.into());
    dst.insert(sysfun::write, BuiltIn::write.into());
    dst.insert(sysfun::monitor, BuiltIn::monitor.into());
    dst.insert(sysfun::debug, BuiltIn::debug.into());
    dst.insert(sysfun::fclose, BuiltIn::fclose.into());
    dst.insert(sysfun::fopen, BuiltIn::fopen.into());
    dst.insert(sysfun::fdisplay, BuiltIn::fdisplay.into());
    dst.insert(sysfun::fwrite, BuiltIn::fwrite.into());
    dst.insert(sysfun::fstrobe, BuiltIn::fstrobe.into());
    dst.insert(sysfun::fmonitor, BuiltIn::fmonitor.into());
    dst.insert(sysfun::fgets, BuiltIn::fgets.into());
    dst.insert(sysfun::fscanf, BuiltIn::fscanf.into());
    dst.insert(sysfun::swrite, BuiltIn::swrite.into());
    dst.insert(sysfun::sformat, BuiltIn::sformat.into());
    dst.insert(sysfun::sscanf, BuiltIn::sscanf.into());
    dst.insert(sysfun::rewind, BuiltIn::rewind.into());
    dst.insert(sysfun::fseek, BuiltIn::fseek.into());
    dst.insert(sysfun::ftell, BuiltIn::ftell.into());
    dst.insert(sysfun::fflush, BuiltIn::fflush.into());
    dst.insert(sysfun::ferror, BuiltIn::ferror.into());
    dst.insert(sysfun::feof, BuiltIn::feof.into());
    dst.insert(sysfun::fdebug, BuiltIn::fdebug.into());
    dst.insert(sysfun::finish, BuiltIn::finish.into());
    dst.insert(sysfun::stop, BuiltIn::stop.into());
    dst.insert(sysfun::fatal, BuiltIn::fatal.into());
    dst.insert(sysfun::warning, BuiltIn::warning.into());
    dst.insert(sysfun::error, BuiltIn::error.into());
    dst.insert(sysfun::info, BuiltIn::info.into());
    dst.insert(sysfun::abstime, BuiltIn::abstime.into());
    dst.insert(sysfun::dist_chi_square, BuiltIn::dist_chi_square.into());
    dst.insert(sysfun::dist_exponential, BuiltIn::dist_exponential.into());
    dst.insert(sysfun::dist_poisson, BuiltIn::dist_poisson.into());
    dst.insert(sysfun::dist_uniform, BuiltIn::dist_uniform.into());
    dst.insert(sysfun::dist_erlang, BuiltIn::dist_erlang.into());
    dst.insert(sysfun::dist_normal, BuiltIn::dist_normal.into());
    dst.insert(sysfun::dist_t, BuiltIn::dist_t.into());
    dst.insert(sysfun::random, BuiltIn::random.into());
    dst.insert(sysfun::arandom, BuiltIn::arandom.into());
    dst.insert(sysfun::rdist_chi_square, BuiltIn::rdist_chi_square.into());
    dst.insert(sysfun::rdist_exponential, BuiltIn::rdist_exponential.into());
    dst.insert(sysfun::rdist_poisson, BuiltIn::rdist_poisson.into());
    dst.insert(sysfun::rdist_uniform, BuiltIn::rdist_uniform.into());
    dst.insert(sysfun::rdist_erlang, BuiltIn::rdist_erlang.into());
    dst.insert(sysfun::rdist_normal, BuiltIn::rdist_normal.into());
    dst.insert(sysfun::rdist_t, BuiltIn::rdist_t.into());
    dst.insert(sysfun::clog2, BuiltIn::clog2.into());
    dst.insert(sysfun::ln, BuiltIn::ln.into());
    dst.insert(sysfun::log10, BuiltIn::log10.into());
    dst.insert(sysfun::exp, BuiltIn::exp.into());
    dst.insert(sysfun::sqrt, BuiltIn::sqrt.into());
    dst.insert(sysfun::pow, BuiltIn::pow.into());
    dst.insert(sysfun::floor, BuiltIn::floor.into());
    dst.insert(sysfun::ceil, BuiltIn::ceil.into());
    dst.insert(sysfun::sin, BuiltIn::sin.into());
    dst.insert(sysfun::cos, BuiltIn::cos.into());
    dst.insert(sysfun::tan, BuiltIn::tan.into());
    dst.insert(sysfun::asin, BuiltIn::asin.into());
    dst.insert(sysfun::acos, BuiltIn::acos.into());
    dst.insert(sysfun::atan, BuiltIn::atan.into());
    dst.insert(sysfun::atan2, BuiltIn::atan2.into());
    dst.insert(sysfun::hypot, BuiltIn::hypot.into());
    dst.insert(sysfun::sinh, BuiltIn::sinh.into());
    dst.insert(sysfun::cosh, BuiltIn::cosh.into());
    dst.insert(sysfun::tanh, BuiltIn::tanh.into());
    dst.insert(sysfun::asinh, BuiltIn::asinh.into());
    dst.insert(sysfun::acosh, BuiltIn::acosh.into());
    dst.insert(sysfun::atanh, BuiltIn::atanh.into());
    dst.insert(sysfun::temperature, BuiltIn::temperature.into());
    dst.insert(sysfun::vt, BuiltIn::vt.into());
    dst.insert(sysfun::simparam, BuiltIn::simparam.into());
    dst.insert(sysfun::simprobe, BuiltIn::simprobe.into());
    dst.insert(sysfun::discontinuity, BuiltIn::discontinuity.into());
    dst.insert(sysfun::limit, BuiltIn::limit.into());
    dst.insert(sysfun::bound_step, BuiltIn::bound_step.into());
    dst.insert(sysfun::mfactor, BuiltIn::mfactor.into());
    dst.insert(sysfun::xposition, BuiltIn::xposition.into());
    dst.insert(sysfun::yposition, BuiltIn::yposition.into());
    dst.insert(sysfun::angle, BuiltIn::angle.into());
    dst.insert(sysfun::hflip, BuiltIn::hflip.into());
    dst.insert(sysfun::vflip, BuiltIn::vflip.into());
    dst.insert(sysfun::param_given, BuiltIn::param_given.into());
    dst.insert(sysfun::port_connected, BuiltIn::port_connected.into());
    dst.insert(sysfun::analog_node_alias, BuiltIn::analog_node_alias.into());
    dst.insert(sysfun::analog_port_alias, BuiltIn::analog_port_alias.into());
    dst.insert(sysfun::value_plusargs, BuiltIn::value_plusargs.into());
    dst.insert(sysfun::simparam_str, BuiltIn::simparam_str.into());
}
