[package]
name = "linker"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"
readme = "../README.md"
rust-version = "1.56"

[lib]
doctest = false

[dependencies]
target = { version = "0.0.0", path = "../target" }
anyhow = "1"
camino = "1.1.2"
cc = "1.0.79"
