#!/bin/csh
echo "-------------------------------------------"
echo "Generate nmos and pmos specific templates  "
echo "-------------------------------------------"

cd ./scripts
./gen_nmos_pmos_tests
cd ..

echo "-------------------------------------------"
echo "Start running all tests.                   "
echo "-------------------------------------------"

foreach dev (sym_nmos asym_nmos sym_pmos asym_pmos)

 echo "-------------------------------------------"
 date
 echo "Run all tests for $dev"
 echo "-------------------------------------------"

 touch vacode/*

 cd $dev && rm -rf ./results/$1
 make -f Makefile $1
 cd ..

end

echo "-------------------------------------------"
date
echo "Finished running all tests                 "
echo "-------------------------------------------"

