#!/bin/csh

#foreach sim (eldo adsSiMKit spectre spectreSiMKit)
foreach sim (ads)

echo "\n====================== \n"
echo "TEST $sim : \n"
echo "====================== \n"
touch vacode/*
date
echo "start: "
date
time ./run_all_tests $sim > run_all_tests_$sim.out
echo "finished: "
date

end

echo "\n================================ \n"
echo "Overview of simulation failures: \n"
echo "================================ \n"
grep failure run_all_tests_*.out

